# *** These filenames must stay in synch with those in $DSP/src/lib/dsp.h ***

INSTALL_ROOT = ${DSTROOT}

default_target:: all

OBJROOT=.
SYMROOT=.

# binary installation directories
LOCAL_DSP_INSTALL_ROOT = $(HOME)/dsp_proj/dsp
#NEXT_DSP_INSTALL_ROOT = ${DSTROOT}/usr/local/lib/dsp
#CCRMA_DSP_INSTALL_ROOT = ${DSTROOT}/usr/lib/dsp
DSP_INSTALL_ROOT = ${DSTROOT}/usr/local/lib/dsp

# source installation directories
SOURCE_DIR = ${SRCROOT}
BIN_SOURCE_DIR = ${SRCROOT}/src/bin
TOOL_SOURCE_DIR = ${SRCROOT}/tools

DSP_SYSTEM_INSTALL_DIR = ${DSTROOT}/usr/local/lib/dsp/monitor
# in smsrc/Makefile: LOCAL_DSP_SYSTEM_INSTALL_DIR = ../monitor

BINDIR = $(INSTALL_ROOT)/usr/local/bin
LOCAL_BINDIR = $(INSTALL_ROOT)/usr/local/bin

# where project release notes are to be installed
# RELNOTES_DIR = ${DSTROOT}/usr/local/RelNotes
RELNOTES_DIR = ${DSTROOT}/LocalLibrary/Documentation/MusicKit/ReleaseNotes

# *** NOTE *** SMSRC_SOURCE_DIR MUST AGREE WITH THE -I DIR IN dspasm-run
# for installsrc::
SMSRC_SOURCE_DIR = ${SOURCE_DIR}/smsrc
LIBDSP_SRC_DIR = ${SOURCE_DIR}/src/lib

# for installhdrs::
INC_DIR = $(INSTALL_ROOT)/LocalDeveloper/Headers

# flags for install
IFLAGS = -q -c
BINIFLAGS = -s

# for install::
# .a files:
LIBA_DIR = $(INSTALL_ROOT)/usr/local/lib
# .shlib files:
SHLIBDIR = $(INSTALL_ROOT)/usr/local/shlib
#CCRMA_SMSRC_INSTALL_DIR = ${CCRMA_DSP_INSTALL_ROOT}/smsrc
#NEXT_SMSRC_INSTALL_DIR = ${NEXT_DSP_INSTALL_ROOT}/smsrc
SMSRC_INSTALL_DIR = ${DSP_INSTALL_ROOT}/smsrc

install::

${SOURCE_DIR}/$(NAME) ${SOURCE_DIR}/bin $(BIN_SOURCE_DIR) $(LOCAL_BINDIR) \
	${SOURCE_DIR}/$(NAME)/test $(SHLIBDIR) \
	$(DSP_SYSTEM_INSTALL_DIR) $(INC_DIR) $(DSTROOT) $(SMSRC_SOURCE_DIR) \
	$(DSP_INSTALL_ROOT)/$(NAME) $(SMSRC_INSTALL_DIR) $(BINDIR) \
	$(SOURCE_DIR) $(RELNOTES_DIR) $(BIN_SOURCE_DIR)/$(NAME) \
	$(TOOL_SOURCE_DIR)/$(NAME) $(BOOT_BIN_DIR_BIN) $(LIBA_DIR)::
	mkdirs -m 755 $@

.SUFFIXES: .o .c .s .dsp .img .asm .lod .lnk .snd

.lod.dsp:
	dspimg $*.lod $@

../../smsrc/mkmon8k.dsp: 
	(cd ../../smsrc ; make mkmon8k.dsp)
