#ifndef __MK_In1qpUG_H___
#define __MK_In1qpUG_H___
/* This is a prototype of the class interface you will write.
   Generated by dspwrap.*/

#import <MusicKit/MKUnitGenerator.h>

@interface In1qpUG : MKUnitGenerator
{
    int qpSatellite;
    BOOL _set;
}

- setChannel:(int)aChan;
/* 0-based channel */

- setScale:(double)val;
/* Scaling */

- setSatellite:(char)sat;
/* 'A','B','C' or 'D'. Default is 'A'. */

- setOutput:(id)aPatchPoint;
/* output location */

- init;
- idleSelf;
- runSelf;

@end

#endif
