#ifndef __MK_TablookiUG_H___
#define __MK_TablookiUG_H___
/* This is a prototype of the class interface you will write.
   Generated by dspwrap.*/

#import <MusicKit/MKUnitGenerator.h>

@interface TablookiUG : MKUnitGenerator
{
}

+(BOOL)shouldOptimize:(unsigned) arg;
- setInput:(id)aPatchPoint;
- setOutput:(id)aPatchPoint;
- setLookupTable:(id)aSynthData;
- idleSelf;

@end
#endif
