
/* Generated by Interface Builder */

#import <objc/Object.h>

@interface MyObject:Object
{
	int numQuarterNotes;
	int numEighthNotes;
	int numSixteenthNotes;
	int numPitchesEnabled;
	unsigned char pitchMode[12];
	double tempo;
}

- setNumQuarterNotes:sender;
- setNumEighthNotes:sender;
- setNumSixteenthNotes:sender;
- setTempoFrom:sender;
- setMode:sender;
- compute:sender;
- play:sender;

@end
