/*
  $Id$
  Defined In: The MusicKit

  Description:
    This is a minimal implementation of OrchloopbeginUG.m, a subclass of MKUnitGenerator.
    It was auto-generated by dspwrap from DSP source code.
    This file and OrchloopbeginUG.h should be extended and rewritten to provide a
    higher level, device-independent interface to the MKSynthPatch programmer.
    See MKUnitGenerator.h and the MKUnitGenerator spec
    for more information regarding unit-generator method design.

  Original Author: David Jaffe

  Copyright (c) 1988-1992, NeXT Computer, Inc.
  Portions Copyright (c) 1994 NeXT Computer, Inc. and reproduced under license from NeXT
  Portions Copyright (c) 1994 Stanford University
*/
/*
Modification history:

  $Log$
  Revision 1.4  2001/09/06 21:27:48  leighsmith
  Merged RTF Reference documentation into headerdoc comments and prepended MK to any older class names

  Revision 1.3  1999/08/26 19:59:31  leigh
  doco correction

  Revision 1.2  1999/07/29 01:25:55  leigh
  Added Win32 compatibility, CVS logs, SBs changes

*/

#import "OrchloopbeginUG.h"

@implementation OrchloopbeginUG:MKUnitGenerator
{
	/* Instance variables go here */

}

#import "orchloopbeginUGInclude.m"

@end
