
/* Generated by Interface Builder */

#import <Foundation/NSObject.h>
#import <Foundation/NSUserDefaults.h>
#import <AppKit/NSGraphics.h>
#import "EnvelopeView.h"

@interface Controller:NSObject
{
	id myListener;
	id infoPanel;
	id helpPanel;
	
    id theSplitView;
	id theWindow;
	
	id theOutputTypes;
	
	id thePoint;
	id theXCoord;
	id theYCoord;
	id theYrCoord;
	id theXMinCoord;
	id theYMinCoord;
	id theXMaxCoord;
	id theYMaxCoord;
	id theXSnapCoord;
	id theYSnapCoord;
	id theStickyPoint;
	id theSmoothing;
	id theSmoothSlider;
	id theGraphType;
	id theLinkX;
	
	EnvelopeView *theEnvelope;
	EnvelopeView *lastDeleted;
}

- (void)applicationDidFinishLaunching:(NSNotification *)notification;
- (void)infoPanel:sender;
- (void)helpPanel:sender;

- (void)addEnvelope:sender;
- (void)removeEnvelope:sender;
- (void)unRemoveEnvelope:sender;

- (void)copy:(id)sender;
- (void)paste:(id)sender;

// Received from current envelope view to update panel info if necessary

- (void)update:sender;
- updateCoords: sender at: (int)point;

// Messages received from panel buttons and pop up lists

- (void)nextPoint:sender;
- (void)previousPoint:sender;

- (void)setPoint:sender;
- (void)setXValue:sender;
- (void)setYValue:sender;
- (void)setYrValue:sender;
- (void)setSmoothValue:sender;
- (void)setSmoothFromSlider:sender;
- (void)broadcastXLimitsOf:envelope;
- (void)setXMinValue:sender;
- (void)setXMaxValue:sender;
- (void)setYMinValue:sender;
- (void)setYMaxValue:sender;
- (void)setXSnapValue:sender;
- (void)setYSnapValue:sender;
- (void)setStickyPoint:sender;
- (void)setGraphType:sender;
- (void)setDrawSegmentsState:sender;
- (void)setLinkX:sender;

- (void)reScaleLimits:sender;

- (NSString *) getStyle;

@end
