# -*- Makefile -*-
#
# $Id$
#
# Build script for the MusicKit Applications on GNUstep systems.
# See Makefile.in for the build process on MacOS X systems.
#
# Leigh Smith <leigh@leighsmith.com>
#
# Copyright (c) 2009, The MusicKit Project.  All rights reserved.
#
# Permission is granted to use and modify this code for commercial and 
# non-commercial purposes so long as the author attribution and copyright 
# messages remain intact and accompany all relevant code.
#
SUBPROJECTS = TwoWaves\
	      Spectro\
	      ScorePlayer\
	      PianoRoll\
	      EnvelopeEd

include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/aggregate.make

