
/* Generated by Interface Builder */

#import "ModView.h"

@implementation ModView

- setFFTControler:anObject
{
    FFTControler = anObject;
    return self;
}

- afterUp:(float*)data length:(int)aLength
{
    [FFTControler setMod:FuncTable];
    return self;
}

- drawSelf:(NXRect *) rect : (int) rectCount
{
    NXRect newVis;

    [self getVisibleRect:&newVis];
    [super drawSelf:rect :rectCount];
    if(!block)[FFTControler passDraw:newVis.origin.x :1.];
    else block = 0;
    return self;
}

- drawSelfAux:(float)origin
{
    static NXRect newVis;
    static int first=1;

    if(first) { [self getVisibleRect:&newVis]; first = 0 ;}
    newVis.origin.x = origin;
    block = 1; 
    [self scrollRectToVisible:&newVis];
    block = 0;
    return self;
}

@end
