#ifndef __MK_ModView_H___
#define __MK_ModView_H___

/* Generated by Interface Builder */

#import "FuncView.h"
#import "FFTControl.h"

@interface ModView:FuncView
{
    id	FFTControler;
    int block;
}

- setFFTControler:anObject;
- afterUp:(float*)data length:(int)aLength;
- drawSelf:(NSRect *)rect : (int)rectCount;
- drawSelfAux:(float)origin;

@end
#endif
