
/* Generated by Interface Builder */

#import <math.h>
#import "Document.h"
#import "PartView.h"
#import <AppKit/NSScrollView.h>
#import <objc/List.h>

#import <stdlib.h>
#import <string.h>
#define MAXFREQ 7040
#define DEFAULT_FREQSCALE 64

@implementation Document

- initScore: (MKScore *) aScore
{
	NSRect aRect;
	NSSize aSize, cSize;
	id bigScroll;
	
	[super init];
	theScore = [aScore retain];
	
	cSize.width = 500.0;
	cSize.height = log(MAXFREQ)*DEFAULT_FREQSCALE/2;
	aSize = [NSScrollView frameSizeForContentSize:cSize hasHorizontalScroller:YES hasVerticalScroller:YES borderType:NSNoBorder];
	docWindow = [NSWindow alloc];
	aRect = NSMakeRect(400.0, 400.0, aSize.width, aSize.height);
	[docWindow initWithContentRect:aRect styleMask:NSResizableWindowMask|(NSMiniaturizableWindowMask |
							NSClosableWindowMask) backing:NSBackingStoreBuffered defer:YES];
	[docWindow setDelegate:self];

	bigScroll = [[NSScrollView alloc] init];
	[bigScroll setHasHorizontalScroller:YES];
	[bigScroll setHasVerticalScroller:YES];
	[docWindow setContentView:bigScroll];
	
	partView = [[PartView alloc] initScore:theScore];
	[bigScroll setDocumentView:partView];
	[bigScroll setBackgroundColor:[NSColor darkGrayColor]];
	
	[docWindow makeKeyAndOrderFront:self];
	return self;
}
-dealloc
{
    [theScore release];
    [partView release];
}

- partView
{
	return partView;
}

- docWindow
{
	return docWindow;
}

- setName:(NSString *)theName
{
    [name release];
    name = [theName copy];
    return self;
}

- (NSString *)whatName
{
    return name;
}

- whatScore
{
	return theScore;
}

- (BOOL)isCurrent
{
	return current;
}

#warning NotificationConversion: windowDidBecomeMain:(NSNotification *)notification is an NSWindow notification method (used to be a delegate method); delegates of NSWindow are automatically set to observe this notification; subclasses of NSWindow do not automatically receive this notification
- (void)windowDidBecomeMain:(NSNotification *)notification
{
	NSWindow *theWindow = [notification object];
    current = YES;
}

#warning NotificationConversion: windowDidResignMain:(NSNotification *)notification is an NSWindow notification method (used to be a delegate method); delegates of NSWindow are automatically set to observe this notification; subclasses of NSWindow do not automatically receive this notification
- (void)windowDidResignMain:(NSNotification *)notification
{
	NSWindow *theWindow = [notification object];
    current = NO;
}

- (NSSize)windowWillResize:(NSWindow *)sender toSize:(NSSize)frameSize
{
	NSSize aSize, cSize;
	NSRect aRect, bRect;

	cSize.width = 500.0;
	cSize.height = log(MAXFREQ)*[[[sender contentView] documentView] freqScale];
	aSize = [NSScrollView frameSizeForContentSize:cSize hasHorizontalScroller:YES hasVerticalScroller:YES borderType:NSNoBorder];
	bRect = NSMakeRect(0.0, 0.0, aSize.width, aSize.height);
	aRect = [NSWindow frameRectForContentRect:bRect styleMask:NSResizableWindowMask];
	if (frameSize.height > aRect.size.height)
		frameSize.height = aRect.size.height;
	return frameSize;
}

@end
