
/* Generated by Interface Builder */

#import <Foundation/NSObject.h>
#import <AppKit/NSWindow.h>
#import <MusicKit/MusicKit.h>

@interface Document:NSObject
{
	id docWindow;
	id partView;
	MKScore *theScore;
	NSString *name;
	BOOL current;
}

- initScore: (MKScore *) aScore;
- partView;
- docWindow;
- setName: (NSString *) theName;
- (NSString *) whatName;
- whatScore;
- (BOOL) isCurrent;

#warning NotificationConversion: windowDidBecomeMain:(NSNotification *)notification is an NSWindow notification method (used to be a delegate method); delegates of NSWindow are automatically set to observe this notification; subclasses of NSWindow do not automatically receive this notification
- (void)windowDidBecomeMain:(NSNotification *)notification;
#warning NotificationConversion: windowDidResignMain:(NSNotification *)notification is an NSWindow notification method (used to be a delegate method); delegates of NSWindow are automatically set to observe this notification; subclasses of NSWindow do not automatically receive this notification
- (void)windowDidResignMain:(NSNotification *)notification;
- (NSSize)windowWillResize:(NSWindow *)sender toSize:(NSSize)frameSize;

@end
