/* Generated by the NeXT Interface Builder */

#import <AppKit/AppKit.h>
#import <MusicKit/MusicKit.h>

@interface MidiLoop : NSObject
{
    MKMidi *midiObj;
    id infoPanel;
    id stringTable;
}

- (void) applicationWillTerminate: (NSNotification *) aNotification;
- go:sender;
- showInfoPanel:sender;

@end
