/* Generated by the NeXT Interface Builder */

#import <AppKit/AppKit.h>
#import <MusicKit/MusicKit.h>

@interface MidiLoop : NSApplication
{
    MKMidi *midiObj;
    id infoPanel;
    id stringTable;
}

- (void)terminate:(id)sender;
- go:sender;
- showInfoPanel:sender;

@end
