/* Generated by the NeXT Interface Builder */

#import <AppKit/AppKit.h>
#import <MusicKit/MusicKit.h>

@interface MidiLoop : NSObject
{
    MKMidi *midiObj;
    IBOutlet NSPanel *infoPanel;
}

- (void) applicationWillTerminate: (NSNotification *) aNotification;
- go: sender;
- showInfoPanel: sender;

@end
