/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

#import "MidiLoop.h"

void main(int argc, char *argv[]) {

    [MidiLoop sharedApplication];
    if ([NSBundle loadNibNamed:@"MidiLoop.nib" owner:NSApp])
	    [NSApp run];
	    
    [NSApp release];
    exit(0);
}
