#!/bin/zsh
DRIVER=ZilogSCCMIDI
SOURCE_DIR=.

sync; sync; sync;
/bin/rm -r /usr/Devices/$DRIVER.config
/bin/cp -r $SOURCE_DIR/$DRIVER.config /usr/Devices

ls -l /usr/Devices/$DRIVER.config

# To load and initialize the driver the simple way:
/usr/sbin/driverLoader d=$DRIVER > /dev/tty  << EOF
y
y
y
y
EOF

sleep 5
tail /var/log/system.log

/usr/sbin/kl_util -s $DRIVER

