#!/bin/zsh
DRIVER=ZilogSCCMIDIDriver
SOURCE_DIR=~leigh/Sources/Drivers/MIDI/$DRIVER
TEST_DIR=$SOURCE_DIR/Testing/
TEST_MACHINE=tzara

sync; sync; sync;
/bin/rm -r /usr/Devices/$DRIVER.config
/bin/cp -r $SOURCE_DIR/$DRIVER.config /usr/Devices
/bin/cp $SOURCE_DIR/Instance0.table /usr/Devices/$DRIVER.config

ls -l /usr/Devices/$DRIVER.config

# To load and initialize the driver the simple way:
/usr/sbin/driverLoader d=$DRIVER > /dev/tty  << EOF
y
y
y
y
EOF

sleep 5
tail /var/log/system.log

/usr/sbin/kl_util -s $DRIVER
rm /usr/Devices/$DRIVER.config/Instance0.table

# debugging
#rcp tzara:/usr/Devices/$DRIVER.config/$DRIVER_loadable $TEST_DIR

