#ifndef __MK_PerformerController_H___
#define __MK_PerformerController_H___

/* Generated by the NeXT Interface Builder */

#import <AppKit/AppKit.h>

@interface PerformerController : NSObject
{
    id stringTable;
    id infoPanel;
}
- terminate:sender;
- setOctave:sender;
- setSpeed:sender;
- appDidInit:sender;
- pauseOrResume:sender;
- showInfoPanel:sender;
@end


#endif
