/* Generated by the NeXT Interface Builder */

#import <AppKit/AppKit.h>
#import <MusicKit/MusicKit.h>

@interface MidiRecord : NSApplication
{
    MKMidi *midiIn;
    id score,scoreRecorder;
    char *fileName;
    id myWindow;
    id infoPanel;
    id saveAsMenuItem;
    id saveMenuItem;
    id theButton;
    id stringTable;
}

- (void)terminate:(id)sender;
- (void)go:sender;
- (void)saveAs:sender;
- (void)save:sender;
- (void)showInfoPanel:sender;

@end
