
/* Generated by the NeXT Interface Builder */

#import <appkit/appkit.h>
#import <appkit/Application.h>

@interface MyApp : Application
{
    id myFilter;
    id midi;
    id infoPanel;
    id stringTable;
}
- setMidiDev:sender;
- go:sender;
- setDelayFrom:sender;
- showInfoPanel:sender;

@end
