
/* Generated by Interface Builder */

#import <objc/Object.h>

@interface Reicher:Object
{
}

- setup;
- StartAndStop:sender;
- doPulsing;
- doCanon;
- doPhasing;
- doInterlock;
- setPulsing:sender;
- setCanon:sender;
- setPhasing:sender;
- setInterlock:sender;

@end
