#!/bin/sh
# $Id$
# Create a set of HTML pages suitable for distribution on the
# web-site. We do this with a customised stylesheet (in DSSSL)
# to produce the correct text coloring, background images etc.
#
# Leigh Smith <leigh@tomandandy.com>
#

JADE=jade

# HTML_DISTRIB_DIR makes it easier to install into SourceForge.
HTML_DISTRIB_DIR=htdocs
HTML_TMPDIR=/tmp/$HTML_DISTRIB_DIR
HTML_TARBALL=/tmp/MusicKitREADME.tar.gz

PDF_TMPDIR=/tmp/mkpdf

# Assume we are standing at the top of the source tree, since with NFS
# it's a bit hard to be universal with paths.
MKSRCDIR=`pwd`
MKDOCDIR=$MKSRCDIR/Documentation
MKREADMESRC=$MKDOCDIR/MusicKit_README.sgml
MKCONCEPTS=$MKDOCDIR/Concepts/
MKTUTORIALS=$MKDOCDIR/TutorialClasses/
MKPUBLICATIONS=$MKDOCDIR/Publications/
MKHEADERDOC=$MKDOCDIR/HeaderDoc/
MK_STYLEDIR=$MKDOCDIR/SGML
MK_STYLESHEET=$MK_STYLEDIR/MusicKit_README.dsssl
MKCONCEPTS_STYLESHEET=/usr/lib/sgml/stylesheets/cygnus-both.dsl
MKTUTORIALS_STYLESHEET=$MKCONCEPTS_STYLESHEET

#
# Convert all SGML to HTML and package
#
mkdir $HTML_TMPDIR
cd $HTML_TMPDIR
$JADE -t sgml -ihtml -d ${MK_STYLESHEET}\#html $MKREADMESRC
ln -s readme.html index.html
cp $MK_STYLEDIR/Images/*.{gif,jpg,png} .

#
# Generate the Concepts Book underneath the README directory, so it
# can be referenced by URL independent of the README directory.
#
mkdir -p $HTML_TMPDIR/MusicKitConcepts/Images
cd $HTML_TMPDIR/MusicKitConcepts
$JADE -t sgml -ihtml -d ${MKCONCEPTS_STYLESHEET}\#html $MKCONCEPTS/MusicKitConcepts.sgml
cp -r $MKCONCEPTS/Images/*.gif Images
ln -s musickitconcepts.html index.html

#
# Generate the tutorials and also place them under the README directory.
#
mkdir -p $HTML_TMPDIR/TutorialClasses/Images
cd $HTML_TMPDIR/TutorialClasses
$JADE -t sgml -ihtml -d ${MKTUTORIALS_STYLESHEET}\#html $MKTUTORIALS/MusicKitTutorials.sgml
cp -r $MKTUTORIALS/Images/*.gif Images
ln -s musickittutorials.html index.html

#
# Run HeaderDoc over the frameworks
#
mkdir $HTML_TMPDIR/Frameworks
cd $MKHEADERDOC
# The MacOS X version of the MKPerformSndMIDI framework is the definitive documentation version.
headerdoc2html -o $HTML_TMPDIR/Frameworks/MKPerformSndMIDI $MKSRCDIR/Frameworks/PlatformDependent/MKPerformSndMIDI_MacOSX

#
# Now create the PDF of the README
#
mkdir $PDF_TMPDIR
cd $PDF_TMPDIR 
cp $MK_STYLEDIR/Images/*.eps .
db2dvi $MKREADMESRC
PDFFINAL=`basename $MKREADMESRC .sgml`.pdf
dvips -o intermediate.ps MusicKit_README.dvi
# This allows us to incorporate any special postscript fonts.
#psprepare intermediate.ps prepared.ps
cp intermediate.ps prepared.ps
ps2pdf prepared.ps /tmp/$PDFFINAL
echo MusicKit README PDF file generated into /tmp/$PDFFINAL
rm -r $PDF_TMPDIR

#
# copy all PDFs to be placed on the web-site, both those prepared and the README
#
mkdir -p $HTML_TMPDIR/Publications
cp $MKPUBLICATIONS/*.pdf $HTML_TMPDIR/Publications
cp /tmp/$PDFFINAL $HTML_TMPDIR

#
# Now create a tarball
#
cd /tmp
tar czf $HTML_TARBALL $HTML_DISTRIB_DIR
echo MusicKit README HTML pages packaged into $HTML_TARBALL
rm -r $HTML_TMPDIR
