#!/bin/zsh
# $Id$
#
# zsh Script to automate the packaging of binaries of the MusicKit frameworks,
# applications, commands and libraries (including Sox) ready for user deployment.
#
# Taken from an article on Stepwise:
# http://www.stepwise.com/Articles/Technical/Packages/BuildingAPackage.html
#
# Leigh Smith <leigh@tomandandy.com> 1999/11/29
#
frameworkname=MK
packagetitle="MusicKit and SndKit Applications and Frameworks"
case `uname` in
    "Darwin")
	packageApplicationsFrom=~/Applications
	installApplicationsInto=/Applications
	packageCommandsFrom=~/Applications
	installCommandsInto=/usr/local/bin
        packageFrameworksFrom=/Library/Frameworks
	packageLibrariesFrom=/usr/local/lib
	osacronym=MOX
	;;
    "Rhapsody")
	packageApplicationsFrom=/Local/Applications
	installApplicationsInto=/Local/Applications
	packageCommandsFrom=/usr/local/bin
	installCommandsInto=/usr/local/bin
        packageFrameworksFrom=/Local/Library/Frameworks
	packageLibrariesFrom=/usr/local/lib
	osacronym=MOXS
	;;
    *)
	echo "Error: unsupported operating system `uname`"
	exit 1;
	;;
esac

if [ x_$1 = x_ ]; then
    echo "Usage: $0 version_number"
    echo "where version_number = V.R.P"
    exit 1;
else
    appversion=$1
fi

# What we package up.
applications=(MIDIFilePlayback.app ScorePlayer.app MidiRecord.app PianoRoll.app)
cmds=(playscore scorefile2stella convertscore playscorefilemidi example1 example3)
# TODO MKUnitGenerators MKSynthPatches
packages=(MusicKit MKPerformSndMIDI MKDSP SndKit)
libraries=(libst.a)

workingdir=/tmp

# Where to install into, for now we assume the location on the
# development machine is the same as on the target installation machine.
install_file_directory=${frameworkname}Install
installRoot=/
installFrameworksInto=$packageFrameworksFrom
installLibrariesInto=$packageLibrariesFrom

cd $workingdir

# Clean out anything already there.
rm -r -f $install_file_directory

# Gather up the packages...
mkdir -p $workingdir/$install_file_directory/$installFrameworksInto
foreach f ($packages)
  cp -R $packageFrameworksFrom/$f.framework $workingdir/$install_file_directory/$installFrameworksInto
end

# ...the libraries...
mkdir -p $workingdir/$install_file_directory/$installLibrariesInto
foreach f ($libraries)
  cp -R $packageLibrariesFrom/$f $workingdir/$install_file_directory/$installLibrariesInto
end

# ...the applications...
mkdir -p $workingdir/$install_file_directory/$installApplicationsInto
foreach f ($applications)
  cp -R $packageApplicationsFrom/$f $install_file_directory/$installApplicationsInto
end

# ...and the commands.
mkdir -p $workingdir/$install_file_directory/$installCommandsInto
foreach f ($cmds)
  cp -R $packageCommandsFrom/$f $install_file_directory/$installCommandsInto
end

# This is the point where you'll want to make sure that the
# permissions and ownership of the files and directories in your
# application are set to the appropriate values. The goal is to set
# all the files to the user-id that you'd expect when they are
# installed by the root user, in most cases you'll want to set the
# ownership to root. Installations by those other than root will
# correctly default to the installer's user-id. The situation with
# respect to permissions is much simpler, since they'll be consistent
# regardless of which user does the installation. To accomplish this,
# you'll need to be logged in as root.

/bin/chmod -R ugo-w $workingdir/$install_file_directory/
/bin/chmod -R ugo+rX $workingdir/$install_file_directory/

# we make the install_file_directory user writable otherwise the installer
# will set the parent directory the application is stored into read-only which
# stops a second reinstall.
/bin/chmod -R u+w $workingdir/$install_file_directory/

echo "Changing ownership to root.wheel, log in as root."
echo "/usr/sbin/chown -R root.wheel $workingdir/$install_file_directory/" | su root -s

#  The .info file is in a basic key/value format. The keys that are
#  commonly used are defined below, a more complete list of keys is
#  available in the Yellow Box release notes
#  (file:/System/Documentation/Developer/YellowBox/ReleaseNotes/CreatingPackages.html).

#  The Title, Version and Description keys are the values displayed in
#  the Installer.app user interface. All are single line strings,
#  including Description.

#  The DefaultLocation key is the destination directory where the
#  contents of the package will be installed. This can be changed by
#  the user if the Relocatable key is set to YES.

#  Some packages should only be installed as root, and those packages
#  will have NeedsAuthorization set to YES. If there is no requirement
#  to be root, you can set this key to NO.

#  If the package is an application, set the Application key to YES,
#  otherwise to No. If you do not want your package contents to be
#  deletable from Installer.app, set InstallOnly to YES. Finally, in
#  most cases, you will want to allow the installation of a package to
#  be stopped during the process. There are cases where that may not
#  be wise (if your application has a packageName.pre_install script
#  for example), and in those cases you'll want to set the DisableStop
#  to YES, otherwise it should be set to NO.

cat > $frameworkname.info << EOF
Title                $packagetitle
Version              $appversion
Description          This package contains frameworks for the $packagetitle.
DefaultLocation      $installRoot
Relocatable          YES
Diskname             $frameworkname #%d
NeedsAuthorization   YES
Application          NO
InstallOnly          NO
DisableStop          NO
RequiresReboot       NO
InstallFat           NO
EOF

# perhaps use DeleteWarning

# If we want the old fashioned (and safer!) way.
# package $install_file_directory $frameworkname.info -gnutar
package $install_file_directory $frameworkname.info

# -d $installRoot

# just tar the file ready for transmission, no point compressing.
shipfile=$workingdir/$frameworkname-$appversion.b.$osacronym.pkg.tar
tar cf $shipfile $frameworkname.pkg

echo "Deleting temporary files, log in as root."
echo "/bin/rm -r -f $workingdir/$install_file_directory" | su root -s

rm -r -f $workingdir/$frameworkname.pkg

echo "Finished. Final package is located at $shipfile"

