#!/bin/sh
# $Id$
# Create a set of HTML pages suitable for distribution on the
# web-site. We do this with a customised stylesheet (in DSSSL)
# to produce the correct text coloring, background images etc.
#
# Leigh Smith <leigh@tomandandy.com>
#

# HTML_DISTRIB_DIR makes it easier to install into SourceForge.
HTML_DISTRIB_DIR=htdocs
TMPDIR=/tmp/$HTML_DISTRIB_DIR
MKSRCDIR=`pwd`
MKSRC=$MKSRCDIR/MusicKit_README.sgml
MK_STYLEDIR=$MKSRCDIR/Documentation/SGML
MK_STYLESHEET=$MK_STYLEDIR/MusicKit_README.dsssl

mkdir $TMPDIR
cd $TMPDIR
jade -t sgml -ihtml -d ${MK_STYLESHEET}\#html $MKSRC
ln -s t1.html index.html
cp $MK_STYLEDIR/Images/* .
cd ..
tar czf MusicKitREADME.tar.gz $HTML_DISTRIB_DIR
echo MusicKit README HTML pages packaged into /tmp/MusicKitREADME.tar.gz
rm -r $TMPDIR

# Now create the PDF
#mkdir $TMPDIR
#cd $TMPDIR 
#cp $MK_STYLEDIR/Images/* .
#db2dvi $MKSRC
#FINAL=`basename $MKSRC .sgml`.pdf
#dvips -o intermediate.ps MusicKit_README.dvi
#psprepare intermediate.ps prepared.ps
#ps2pdf prepared.ps $FINAL
