#!/bin/sh
# $Id$
#
# sh script to automate the secure uploading of the MusicKit
# README tarball from package temporary directory to the
# sourceforge website.
#
# Leigh Smith <leigh@tomandandy.com> 2000/11/28
#
TARBALLLOC=/tmp
TARBALL=MusicKitREADME.tar.gz
SITEUSER=leighsmith
SITE=musickit.sourceforge.net
SITEHTMLDIR=/home/groups/m/mu/musickit

scp $TARBALLLOC/$TARBALL $SITEUSER@$SITE:$TARBALL
ssh -l $SITEUSER $SITE "cd $SITEHTMLDIR; tar xzvf ~/$TARBALL"

