#!/bin/sh
# $Id$
#
# sh script to automate the secure uploading of the MusicKit
# README tarball from package temporary directory to the
# sourceforge website.
#
# Leigh Smith <leigh@leighsmith.com> 2000/11/28
#
TARBALLLOC=/tmp
TARBALL=MusicKitREADME.tar.bz2
SITEUSER=leighsmith
SITE=musickit.sourceforge.net
SITEHTMLDIR=/home/groups/m/mu/musickit

# 
# ftp upload.sourceforge.net
# ftp leigh@leighsmith.com
# cd incoming
# bin
# lcd $TARBALLLOC
# send MK-$MKVERS.s.tar.gz
# send MK-$MKVERS.MOX.b.tar.gz

scp $TARBALLLOC/$TARBALL $SITEUSER@$SITE:$TARBALL
ssh -l $SITEUSER $SITE "cd $SITEHTMLDIR; tar xjf ~/$TARBALL"

