.TH ASM56000 1 "1 June 1987" "Motorola Inc."
.SH NAME
asm56000 \- Motorola DSP56000 Macro Cross Assembler
.SH SYNOPSIS
\fBasm56000\fR
[ \fB-A\fR ]
[ \fB-B\fR[<\fIobjfil\fR>] ]
[ \fB-D\fR<\fIsymbol\fR> <\fIstring\fR> ]
.if n .ti +0.5i
[ \fB-I\fR<\fIipath\fR> ]
[ \fB-L\fR[<\fIlstfil\fR>] ]
[ \fB-M\fR<\fImpath\fR> ]
.ti +0.5i
[ \fB-O\fR<\fIopt\fR>[,<\fIopt\fR>...] ]
<files...>
.SH DESCRIPTION
.I asm56000
is a program that processes source program
statements written in DSP56000 assembly language, translating
these source statements into object programs
compatible with other DSP56000 software products.
.LP
.I files
is a list of operating system compatible filenames (including optional
pathnames) separated by blanks.  If no extension is supplied for a given
file, the assembler will automatically append
.I .asm
to the filename.  If no
path is specified for a given file, the assembler will look for that file
in the current directory.  The list of files will be processed sequentially in
the order given and all files will be used to generate the output listing
and object file.
.SH OPTIONS
Any of the following command line options may be specified.
These can be in any order,
but must precede the list of source filenames.  Option letters may be
specified in either upper or lower case.
.IP \fB\-A\fR
Indicates that the assembler should operate in absolute mode, creating
a load (\fI.lod\fR) file if the \fB\-B\fR option is given.  By default
the assembler produces a link (\fI.lnk\fR) file which is subsequently
processed by the DSP56000 linker.
.IP \fB\-B\fR[<\fIobjfil\fR>]
This option specifies that an object file is to be created for
assembler output.
.I objfil
can be any legal operating system filename,
including an optional pathname.  Note that there can be no intervening
spaces between the 
.B \-B
and the optional filename.
.IP
If a path is not specified, the file will be created in the current
directory.  If no filename is specified, the assembler
will use the basename (filename without extension) of the first filename
encountered in the source input file list.  The resulting output file will
have an extension of \fI.lnk\fR unless the \fB\-A\fR option is given,
in which case the file will have a \fI.lod\fR extension.  If the 
.B \-B
option is not specified, then the assembler will not generate an object
file.  The 
.B \-B
option should
be specified only once.
.IP "\fB-D\fR<\fIsymbol\fR> <\fIstring\fR>"
This is equivalent to a source statement of the form:
.sp
.ti +0.5i
\fBDEFINE \fR<\fIsymbol\fR> <\fIstring\fR>
.sp
The 
.B -D 
and
.I symbol
should not be separated by a blank. 
.I string
should
be enclosed in quotes and preceded by a blank.  
.I string
must be enclosed
in double quotes if it contains any embedded blanks.  The
\fB-D\fR<\fIsymbol\fR> <\fIstring\fR> 
sequence can be repeated as often as desired.
.IP \fB-I\fR<\fIipath\fR>
When the assembler encounters
.I include
files, the current directory (or the directory specified in the
.B INCLUDE
directive) is first searched for the file.  If it is not found and the
.B -I
option is specified, the assembler
prefixes the filename (and optional pathname) specified in the
.B INCLUDE
directive with 
.I ipath
and searches the newly formed directory
pathname for the file.  The
.B -I
and \fIipath\fR should not be separated by a blank.  The directories
will be searched in the reverse order specified on the command line.
.IP \fB-L\fR[<\fIlstfil\fR>]
This option specifies that a listing file is to be created for assembler
output.  
.I lstfil
can be any legal operating system filename, including an
optional pathname.  Note that there can be no intervening spaces between
the 
.B -L
and the optional filename.
.IP
If a path is not specified, the file will be created in the current
directory.  If no filename is specified, the assembler
will use the basename (filename without extension) of the first filename
encountered in the source input file list.  The resulting output file will
have an extension of \fI.lst\fR.  If the 
.B -L
option is not specified,
then the assembler will route listing output to the standard output. The
.B -L
option should be specified only once.
.IP \fB-M\fR<\fImpath\fR>
This is equivalent to a source statement of the form:
.sp
.ti +0.5i
\fBMACLIB \fR<\fImpath\fR>
.sp
The
.B -M 
and 
.I mpath
should not be separated by a blank.  The directories will be
searched in the reverse order specified on the command line.
.IP \fB-O\fR<\fIopt\fR>[,<\fIopt\fR>...]
The 
.B -O
and 
.I opt
should not be separated by a blank.  
.I opt
can be any
of the options that are available with the assembler
.B OPT
directive. 
If multiple options are specified, they must be separated by commas.  The 
\fB-O\fR<\fIopt\fR> 
sequence can be repeated for as many options as desired.
.SH "SEE ALSO"
\fIMotorola DSP56000 Macro Assembler Reference Manual\fR, Motorola Inc., 1987.
.br
lnk56000(1),lib56000(1)
