/* This is a stub of the class you fill in. Generated by dsploadwrap.*/
#import <musickit/musickit.h>
#import "BiquadUG.h"
@implementation BiquadUG:UnitGenerator
{ /* Instance variables go here */
 /* Instance variables go here */
}

   enum args { ainp, aout, s1, s2, bqa1, bqa2, bqb1, bqb2, go2};

- (void)setInput:inputPatchPoint
{
	return [self setAddressArg:ainp to:inputPatchPoint];
}

- (void)setOutput:outputPatchPoint
{
	return [self setAddressArg:aout to:outputPatchPoint];
}

- (void)setGain:(double)aValue
{
	return [self setDatumArg:go2 to:DSPDoubleToFix24(aValue * 0.5)];
}

- (void)setA1:(double)aValue
{
	return [self setDatumArg:bqa1 to:DSPDoubleToFix24(aValue * 0.5)];
}

- (void)setA2:(double)aValue
{
	return [self setDatumArg:bqa2 to:DSPDoubleToFix24(aValue * 0.5)];
}

- (void)setB1:(double)aValue
{
	return [self setDatumArg:bqb1 to:DSPDoubleToFix24(aValue * 0.5)];
}

- (void)setB2:(double)aValue
{
	return [self setDatumArg:bqb2 to:DSPDoubleToFix24(aValue * 0.5)];
}


#import "biquadUGInclude.m"
@end