
/* Generated by Interface Builder */

#import <AppKit/NSApplication.h>

@interface Controller:NSObject
{
    id lipPots;
    id lipFields;
    id myMidiHandler;
}

- (void)play:sender;
- (void)changeVelocity:(double)velocity;
- (void)changeAmps:sender;
- changeAmpsQuick: (double) inValue : (double) outValue;
- (void)changeLip:sender;
- (void)changeSlide:sender;
- changeLipQuick: (double) massValue : (double) springValue;
- (void)changeSlideQuick:(double)value;

@end
