/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

#import <AppKit/AppKit.h>

void main(int argc, char *argv[]) {

    [NSApplication new];
    if ([NSBundle loadNibNamed:@"HosePlayer.nib" owner:NSApp])
	    [NSApp run];
	    
    [NSApp release];
    exit(0);
}
