#ifndef __MK_MIDIometer_H___
#define __MK_MIDIometer_H___

/* Generated by Interface Builder */

#import "EnsembleNoteFilter.h"

@interface MIDIometer:EnsembleNoteFilter
{
	BOOL showPeak[4];
	int peak[4];
	int controller[4];
	id conductor;

    id	controlInterface;
    id	meterView1;
    id	meterView2;
    id	meterView3;
    id	meterView4;
    id	valueField1;
    id	valueField2;
    id	valueField3;
    id	valueField4;
	id	peakButton1;
	id	peakButton2;
	id	peakButton3;
	id	peakButton4;
}

- takePeakFrom:sender;
- takeControllerFrom:sender;

@end
#endif
