#ifndef __MK_QuadPerformer_H___
#define __MK_QuadPerformer_H___

/* Generated by Interface Builder */

#import <musickit/Performer.h>

@interface QuadPerformer:Performer
{
    id	xFractal;
    id	noteFilter;
    id	yFractal;
    float startTime;
    double interval;
}

- setNoteFilter:anObject;
- setInterval:(double)anInterval;
- setFractalX:xObject y:yObject;
- inspectFractal:sender;

@end
#endif
