#ifndef __MK_OscwUG_H___
#define __MK_OscwUG_H___
/* This is a prototype of the class interface you will write.
   Generated by dspwrap.*/

#import <musickit/UnitGenerator.h>

@interface OscwUG : UnitGenerator
{
 /* Instance variables go here */
}

/*
 * Methods for poking the unit generator's DSP memory arguments
 * once it is loaded into the DSP orchestra.
 */
- setC:(DSPDatum)aFix24;
- setU:(DSPDatum)aFix24;
- setOutputAout:(id)aPatchPoint;
- setS:(DSPDatum)aFix24;
- setV:(DSPDatum)aFix24;

/*
 * Method for "turning off" a unit generator by patching all its outputs to "sink" */
- idleSelf;


@end
#endif
