/* This is a minimal implementation of OrchloopbeginUG.m, a subclass of UnitGenerator.
   It was auto-generated by dspwrap from DSP source code.
   This file and OrchloopbeginUG.h should be extended and rewritten to provide a 
   higher level, device-independent interface to the SynthPatch programmer.
   See /usr/include/musickit/MKUnitGenerator.h and the UnitGenerator spec
   for more information regarding unit-generator method design.
*/

#import "OrchloopbeginUG.h"

@implementation OrchloopbeginUG:MKUnitGenerator
{
	/* Instance variables go here */

}

#import "orchloopbeginUGInclude.m"

@end
