/* This source file was auto-generated by dspwrap from dsp macro orchloopbegin.
   It is included by unit generator OrchloopbeginUG. It should not be edited.*/
// LMS unfortunately I had to produce a new MkUnitGenerator #import, but I can't 
//seem to find orchloopbegin anyway :-(
#import <MKUnitGenerator.h>

static MKMasterUGStruct _masterUGStruct = {
   0 /* nArgs */,
   {0,0,0,0,0,0,0,0,0,0,0,0,0} /* globalSymCount */,
   {0,0,0} /* fixupCount */
};

/* times in seconds/sample */
#define COMPUTETIME (18 * (DSP_CLOCK_PERIOD / DSPMK_I_NTICK))
#define OFFCHIP_COMPUTETIME (24 * (DSP_CLOCK_PERIOD / DSPMK_I_NTICK))

static MKLeafUGStruct _leafUGStruct = {
    {0/* xArg  */,  0/* yArg  */,  0/* lArg */,
     9/* pLoop */,  0/* pSubr */,
     0/* xData */,  0/* yData */} /* memory requirements */, COMPUTETIME};

+(MKLeafUGStruct *)classInfo  
{   if (_leafUGStruct.master == NULL)
      _leafUGStruct.master = [self masterUGPtr];
    return &_leafUGStruct; }

+(MKMasterUGStruct *)masterUGPtr { return &_masterUGStruct; }

+ (void)initialize /* Sent once on factory start-up. */
{   static DSPDataRecord _dataRecP = {NULL, DSP_LC_P, 0, 1, 9}; 
   static int _dataP[] = {0xbf080,0x3261,0x60f400,0x5,0x64f400,
                          0x5,0x35f600,0x650400,0x0};
   _leafUGStruct.master = NULL;
   _leafUGStruct.data[(int)DSP_LC_P] = &_dataRecP;
   _dataRecP.data = _dataP;
   MKInitUnitGeneratorClass(&_leafUGStruct);
   _leafUGStruct.reserved1 = MK_2COMPUTETIMES;
   _leafUGStruct.offChipComputeTime = OFFCHIP_COMPUTETIME;
   return;
}
