/*
  $Id$
  Defined In: The MusicKit

  Description:
    These are macros for getting pitches in Hz. Note that you may not set
    these pseudo-variables! They are really method calls. 
 
    For the sake of terseness and convenience of use, we break here from the 
    Music Kit convention of appending MK_ to the start of macros. 

  Original Author: David Jaffe

  Copyright (c) 1988-1992, NeXT Computer, Inc.
  Portions Copyright (c) 1994 NeXT Computer, Inc. and reproduced under license from NeXT
  Portions Copyright (c) 1994 Stanford University.
  Portions Copyright (c) 1999-2004 The MusicKit Project.
*/

#ifndef __MK_pitches_H___
#define __MK_pitches_H___

#import "keynums.h"
#import "MKTuningSystem.h"

#ifndef PITCHES_H
#define PITCHES_H

#define c00  [MKTuningSystem freqForKeyNum: c00k]
#define cs00 [MKTuningSystem freqForKeyNum: cs00k]
#define df00 [MKTuningSystem freqForKeyNum: cs00k]
#define d00  [MKTuningSystem freqForKeyNum: d00k] 
#define ds00 [MKTuningSystem freqForKeyNum: ds00k] 
#define ef00 [MKTuningSystem freqForKeyNum: ds00k] 
#define e00  [MKTuningSystem freqForKeyNum: e00k] 
#define es00 [MKTuningSystem freqForKeyNum: f00k] 
#define ff00 [MKTuningSystem freqForKeyNum: e00k] 
#define f00  [MKTuningSystem freqForKeyNum: f00k] 
#define fs00 [MKTuningSystem freqForKeyNum: fs00k] 
#define gf00 [MKTuningSystem freqForKeyNum: fs00k] 
#define g00  [MKTuningSystem freqForKeyNum: g00k] 
#define gs00 [MKTuningSystem freqForKeyNum: gs00k] 
#define af00 [MKTuningSystem freqForKeyNum: gs00k] 
#define a00  [MKTuningSystem freqForKeyNum: a00k] 
#define as00 [MKTuningSystem freqForKeyNum: as00k] 
#define bf00 [MKTuningSystem freqForKeyNum: as00k] 
#define b00  [MKTuningSystem freqForKeyNum: b00k] 
#define bs00 [MKTuningSystem freqForKeyNum: c0k] 
#define cf0  [MKTuningSystem freqForKeyNum: bs00k] 
#define c0   [MKTuningSystem freqForKeyNum: c0k]
#define cs0  [MKTuningSystem freqForKeyNum: cs0k]
#define df0  [MKTuningSystem freqForKeyNum: cs0k]
#define d0   [MKTuningSystem freqForKeyNum: d0k] 
#define ds0  [MKTuningSystem freqForKeyNum: ds0k] 
#define ef0  [MKTuningSystem freqForKeyNum: ds0k] 
#define e0   [MKTuningSystem freqForKeyNum: e0k] 
#define es0  [MKTuningSystem freqForKeyNum: f0k]
#define ff0  [MKTuningSystem freqForKeyNum: e0k]
#define f0   [MKTuningSystem freqForKeyNum: f0k] 
#define fs0  [MKTuningSystem freqForKeyNum: fs0k] 
#define gf0  [MKTuningSystem freqForKeyNum: fs0k] 
#define g0   [MKTuningSystem freqForKeyNum: g0k] 
#define gs0  [MKTuningSystem freqForKeyNum: gs0k] 
#define af0  [MKTuningSystem freqForKeyNum: gs0k] 
#define a0   [MKTuningSystem freqForKeyNum: a0k] 
#define as0  [MKTuningSystem freqForKeyNum: as0k] 
#define bf0  [MKTuningSystem freqForKeyNum: as0k] 
#define b0   [MKTuningSystem freqForKeyNum: b0k] 
#define bs0  [MKTuningSystem freqForKeyNum: c1k]
#define cf1  [MKTuningSystem freqForKeyNum: b0k] 
#define c1   [MKTuningSystem freqForKeyNum: c1k] 
#define cs1  [MKTuningSystem freqForKeyNum: cs1k]
#define df1  [MKTuningSystem freqForKeyNum: cs1k]
#define d1   [MKTuningSystem freqForKeyNum: d1k]
#define ds1  [MKTuningSystem freqForKeyNum: ds1k]
#define ef1  [MKTuningSystem freqForKeyNum: ds1k]
#define e1   [MKTuningSystem freqForKeyNum: e1k]
#define es1  [MKTuningSystem freqForKeyNum: f1k]
#define ff1  [MKTuningSystem freqForKeyNum: e1k]
#define f1   [MKTuningSystem freqForKeyNum: f1k]
#define fs1  [MKTuningSystem freqForKeyNum: fs1k]
#define gf1  [MKTuningSystem freqForKeyNum: fs1k]
#define g1   [MKTuningSystem freqForKeyNum: g1k]
#define gs1  [MKTuningSystem freqForKeyNum: gs1k]
#define af1  [MKTuningSystem freqForKeyNum: gs1k]
#define a1   [MKTuningSystem freqForKeyNum: a1k]
#define as1  [MKTuningSystem freqForKeyNum: as1k]
#define bf1  [MKTuningSystem freqForKeyNum: as1k]
#define b1   [MKTuningSystem freqForKeyNum: b1k]
#define bs1  [MKTuningSystem freqForKeyNum: c2k]
#define cf2  [MKTuningSystem freqForKeyNum: b1k]
#define c2   [MKTuningSystem freqForKeyNum: c2k]
#define cs2  [MKTuningSystem freqForKeyNum: cs2k]
#define df2  [MKTuningSystem freqForKeyNum: cs2k]
#define d2   [MKTuningSystem freqForKeyNum: d2k]
#define ds2  [MKTuningSystem freqForKeyNum: ds2k]
#define ef2  [MKTuningSystem freqForKeyNum: ds2k]
#define e2   [MKTuningSystem freqForKeyNum: e2k]
#define es2  [MKTuningSystem freqForKeyNum: f2k]
#define ff2  [MKTuningSystem freqForKeyNum: e2k]
#define f2   [MKTuningSystem freqForKeyNum: f2k]
#define fs2  [MKTuningSystem freqForKeyNum: fs2k]
#define gf2  [MKTuningSystem freqForKeyNum: fs2k]
#define g2   [MKTuningSystem freqForKeyNum: g2k]
#define gs2  [MKTuningSystem freqForKeyNum: gs2k]
#define af2  [MKTuningSystem freqForKeyNum: gs2k]
#define a2   [MKTuningSystem freqForKeyNum: a2k]
#define as2  [MKTuningSystem freqForKeyNum: as2k]
#define bf2  [MKTuningSystem freqForKeyNum: as2k]
#define b2   [MKTuningSystem freqForKeyNum: b2k]
#define bs2  [MKTuningSystem freqForKeyNum: c3k]
#define cf3  [MKTuningSystem freqForKeyNum: b2k]
#define c3   [MKTuningSystem freqForKeyNum: c3k]
#define cs3  [MKTuningSystem freqForKeyNum: cs3k]
#define df3  [MKTuningSystem freqForKeyNum: cs3k]
#define d3   [MKTuningSystem freqForKeyNum: d3k]
#define ds3  [MKTuningSystem freqForKeyNum: ds3k]
#define ef3  [MKTuningSystem freqForKeyNum: ds3k]
#define e3   [MKTuningSystem freqForKeyNum: e3k]
#define es3  [MKTuningSystem freqForKeyNum: f3k]
#define ff3  [MKTuningSystem freqForKeyNum: e3k]
#define f3   [MKTuningSystem freqForKeyNum: f3k]
#define fs3  [MKTuningSystem freqForKeyNum: fs3k]
#define gf3  [MKTuningSystem freqForKeyNum: fs3k]
#define g3   [MKTuningSystem freqForKeyNum: g3k]
#define gs3  [MKTuningSystem freqForKeyNum: gs3k]
#define af3  [MKTuningSystem freqForKeyNum: gs3k]
#define a3   [MKTuningSystem freqForKeyNum: a3k]
#define as3  [MKTuningSystem freqForKeyNum: as3k]
#define bf3  [MKTuningSystem freqForKeyNum: as3k]
#define b3   [MKTuningSystem freqForKeyNum: b3k]
#define bs3  [MKTuningSystem freqForKeyNum: c4k]
#define cf4  [MKTuningSystem freqForKeyNum: b3k]
#define c4   [MKTuningSystem freqForKeyNum: c4k]
#define cs4  [MKTuningSystem freqForKeyNum: cs4k]
#define df4  [MKTuningSystem freqForKeyNum: cs4k]
#define d4   [MKTuningSystem freqForKeyNum: d4k]
#define ds4  [MKTuningSystem freqForKeyNum: ds4k]
#define ef4  [MKTuningSystem freqForKeyNum: ds4k]
#define e4   [MKTuningSystem freqForKeyNum: e4k]
#define es4  [MKTuningSystem freqForKeyNum: f4k]
#define ff4  [MKTuningSystem freqForKeyNum: e4k]
#define f4   [MKTuningSystem freqForKeyNum: f4k]
#define fs4  [MKTuningSystem freqForKeyNum: fs4k]
#define gf4  [MKTuningSystem freqForKeyNum: fs4k]
#define g4   [MKTuningSystem freqForKeyNum: g4k]
#define gs4  [MKTuningSystem freqForKeyNum: gs4k]
#define af4  [MKTuningSystem freqForKeyNum: gs4k]
#define a4   [MKTuningSystem freqForKeyNum: a4k]
#define as4  [MKTuningSystem freqForKeyNum: as4k]
#define bf4  [MKTuningSystem freqForKeyNum: as4k]
#define b4   [MKTuningSystem freqForKeyNum: b4k]
#define bs4  [MKTuningSystem freqForKeyNum: c5k]
#define cf5  [MKTuningSystem freqForKeyNum: b4k]
#define c5   [MKTuningSystem freqForKeyNum: c5k]
#define cs5  [MKTuningSystem freqForKeyNum: cs5k]
#define df5  [MKTuningSystem freqForKeyNum: cs5k]
#define d5   [MKTuningSystem freqForKeyNum: d5k]
#define ds5  [MKTuningSystem freqForKeyNum: ds5k]
#define ef5  [MKTuningSystem freqForKeyNum: ds5k]
#define e5   [MKTuningSystem freqForKeyNum: e5k]
#define es5  [MKTuningSystem freqForKeyNum: f5k]
#define ff5  [MKTuningSystem freqForKeyNum: e5k]
#define f5   [MKTuningSystem freqForKeyNum: f5k]
#define fs5  [MKTuningSystem freqForKeyNum: fs5k]
#define gf5  [MKTuningSystem freqForKeyNum: fs5k]
#define g5   [MKTuningSystem freqForKeyNum: g5k]
#define gs5  [MKTuningSystem freqForKeyNum: gs5k]
#define af5  [MKTuningSystem freqForKeyNum: gs5k]
#define a5   [MKTuningSystem freqForKeyNum: a5k]
#define as5  [MKTuningSystem freqForKeyNum: as5k]
#define bf5  [MKTuningSystem freqForKeyNum: as5k]
#define b5   [MKTuningSystem freqForKeyNum: b5k]
#define bs5  [MKTuningSystem freqForKeyNum: c6k]
#define cf6  [MKTuningSystem freqForKeyNum: b5k]
#define c6   [MKTuningSystem freqForKeyNum: c6k]
#define cs6  [MKTuningSystem freqForKeyNum: cs6k]
#define df6  [MKTuningSystem freqForKeyNum: cs6k]
#define d6   [MKTuningSystem freqForKeyNum: d6k]
#define ds6  [MKTuningSystem freqForKeyNum: ds6k]
#define ef6  [MKTuningSystem freqForKeyNum: ds6k]
#define e6   [MKTuningSystem freqForKeyNum: e6k]
#define es6  [MKTuningSystem freqForKeyNum: f6k]
#define ff6  [MKTuningSystem freqForKeyNum: e6k]
#define f6   [MKTuningSystem freqForKeyNum: f6k]
#define fs6  [MKTuningSystem freqForKeyNum: fs6k]
#define gf6  [MKTuningSystem freqForKeyNum: fs6k]
#define g6   [MKTuningSystem freqForKeyNum: g6k]
#define gs6  [MKTuningSystem freqForKeyNum: gs6k]
#define af6  [MKTuningSystem freqForKeyNum: gs6k]
#define a6   [MKTuningSystem freqForKeyNum: a6k]
#define as6  [MKTuningSystem freqForKeyNum: as6k]
#define bf6  [MKTuningSystem freqForKeyNum: as6k]
#define b6   [MKTuningSystem freqForKeyNum: b6k]
#define bs6  [MKTuningSystem freqForKeyNum: c7k]
#define cf7  [MKTuningSystem freqForKeyNum: b6k]
#define c7   [MKTuningSystem freqForKeyNum: c7k]
#define cs7  [MKTuningSystem freqForKeyNum: cs7k]
#define df7  [MKTuningSystem freqForKeyNum: cs7k]
#define d7   [MKTuningSystem freqForKeyNum: d7k]
#define ds7  [MKTuningSystem freqForKeyNum: ds7k]
#define ef7  [MKTuningSystem freqForKeyNum: ds7k]
#define e7   [MKTuningSystem freqForKeyNum: e7k]
#define es7  [MKTuningSystem freqForKeyNum: f7k]
#define ff7  [MKTuningSystem freqForKeyNum: e7k]
#define f7   [MKTuningSystem freqForKeyNum: f7k]
#define fs7  [MKTuningSystem freqForKeyNum: fs7k]
#define gf7  [MKTuningSystem freqForKeyNum: fs7k]
#define g7   [MKTuningSystem freqForKeyNum: g7k]
#define gs7  [MKTuningSystem freqForKeyNum: gs7k]
#define af7  [MKTuningSystem freqForKeyNum: gs7k]
#define a7   [MKTuningSystem freqForKeyNum: a7k]
#define as7  [MKTuningSystem freqForKeyNum: as7k]
#define bf7  [MKTuningSystem freqForKeyNum: as7k]
#define b7   [MKTuningSystem freqForKeyNum: b7k]
#define bs7  [MKTuningSystem freqForKeyNum: c8k]
#define cf8  [MKTuningSystem freqForKeyNum: b7k]
#define c8   [MKTuningSystem freqForKeyNum: c8k]
#define cs8  [MKTuningSystem freqForKeyNum: cs8k]
#define df8  [MKTuningSystem freqForKeyNum: cs8k]
#define d8   [MKTuningSystem freqForKeyNum: d8k]
#define ds8  [MKTuningSystem freqForKeyNum: ds8k]
#define ef8  [MKTuningSystem freqForKeyNum: ds8k]
#define e8   [MKTuningSystem freqForKeyNum: e8k]
#define es8  [MKTuningSystem freqForKeyNum: f8k]
#define ff8  [MKTuningSystem freqForKeyNum: e8k]
#define f8   [MKTuningSystem freqForKeyNum: f8k]
#define fs8  [MKTuningSystem freqForKeyNum: fs8k]
#define gf8  [MKTuningSystem freqForKeyNum: fs8k]
#define g8   [MKTuningSystem freqForKeyNum: g8k]
#define gs8  [MKTuningSystem freqForKeyNum: gs8k]
#define af8  [MKTuningSystem freqForKeyNum: gs8k]
#define a8   [MKTuningSystem freqForKeyNum: a8k]
#define as8  [MKTuningSystem freqForKeyNum: as8k]
#define bf8  [MKTuningSystem freqForKeyNum: as8k]
#define b8   [MKTuningSystem freqForKeyNum: b8k]
#define bs8  [MKTuningSystem freqForKeyNum: c9k]
#define cf9  [MKTuningSystem freqForKeyNum: b8k]
#define c9   [MKTuningSystem freqForKeyNum: c9k]
#define cs9  [MKTuningSystem freqForKeyNum: cs9k]
#define df9  [MKTuningSystem freqForKeyNum: cs9k]
#define d9   [MKTuningSystem freqForKeyNum: d9k]
#define ds9  [MKTuningSystem freqForKeyNum: ds9k]
#define ef9  [MKTuningSystem freqForKeyNum: ds9k]
#define e9   [MKTuningSystem freqForKeyNum: e9k]
#define es9  [MKTuningSystem freqForKeyNum: f9k]
#define ff9  [MKTuningSystem freqForKeyNum: e9k]
#define f9   [MKTuningSystem freqForKeyNum: f9k]
#define fs9  [MKTuningSystem freqForKeyNum: fs9k]
#define gf9  [MKTuningSystem freqForKeyNum: fs9k]
#define g9   [MKTuningSystem freqForKeyNum: g9k]

#endif /* PITCHES_H */

#endif
