#ifndef __MK_PhiView_H___
#define __MK_PhiView_H___

/* Generated by Interface Builder */

#import "FuncView.h"
#import "FFTControl.h"
#import <AppKit/AppKit.h>

@interface PhiView:FuncView
{
    id	FFTControler;
    int block;
}

- setFFTControler:anObject;
- afterUp:(float*)data length:(int)aLength;
- drawSelf:(NSRect *)rect :(int)rectCount;
- drawSelfAux:(float)origin;
@end
#endif
