#ifndef __MK_Wave_H___
#define __MK_Wave_H___

/* Generated by Interface Builder */

#import "FuncView.h"
#import "FFTControl.h"
#import <appkit/appkit.h>	

@interface Wave:FuncView
{
    id fftView;
    id anOrch;
    id aSP;
    id tableLook;	        /* Lookup Table*/
    id aNote;
    int *DSPTable;
    float frq,amp,pvib,rvib,pvibFrq;
    BOOL vibOn;
}

- setFftView:anObject;
- awakeFromNib;
- mouseDown:(NSEvent *) anEvent;
- sawTooth:sender;
- triangle:sender;
- sine:sender;
- square:sender;
- sendFreq:sender;
- sendAmp:sender;
- afterDrag:(float*) data length:(int)aLength offset:(int)anOffset;
- afterUp:(float*)data length:(int)aLength;
- setSound:sender;
- startSound;
- stopSound;
- sendPVibFreq:sender;
- sendPVib:sender;
- sendRVib:sender;
- vibOnOff:sender;

@end
#endif
