#ifndef __MK_RampUG_H___
#define __MK_RampUG_H___
/* This is a stub of the class interface you fill in. 
   Generated by dsploadwrap.*/
#import <musickit/UnitGenerator.h>
@interface RampUG : UnitGenerator
{ /* Instance variables go here */ }

-setOutput:aPatchPoint;
-setSlope:(double)aVal;
-setCurVal:(double)aVal;
-setConstant:(double)aVal;
-idleSelf;

@end

#endif
