#ifndef __MK_SineGen_H___
#define __MK_SineGen_H___

/* Generated by Interface Builder */

#import <objc/Object.h>

@interface SineGen:Object
{
    id	centerSlider;
    id	centerTextField;
    id  widthSlider;
    id  widthTextField;
    id  durationSlider;
    id  durationTextField;
    id  attenuationSlider;
    id  attenuationTextField;
    id  orch;
    id  outl;
    id  outr;
    id  osc;
    id  amp;
    id  inc;
    id  myAnimator;
    id  infoPanel;
    id  stringTable;
    BOOL running;
}

- showInfoPanel:sender;
- setUp;
- sweep: sender;
- start:sender;
- updateCenter:sender;
- updateWidth:sender;
- updateDuration:sender;
- updateAttenuation:sender;
@end

#endif
