/* This is a stub of the class interface you fill in. Generated by dsploadwrap.*/
#import <MusicKit/MKUnitGenerator.h>
@interface BiquadUG : MKUnitGenerator
{ /* Instance variables go here */  /* Instance variables go here */ }

- (void)setInput:inputPatchPoint;
- (void)setOutput:outputPatchPoint;
- (void)setGain:(double)aValue;
- (void)setA1:(double)aValue;
- (void)setA2:(double)aValue;
- (void)setB1:(double)aValue;
- (void)setB2:(double)aValue;

@end
