/* This source file was auto-generated by dspwrap from dsp macro biquad.
   It is included by unit generator BiquadUG. It should not be edited.*/
#import <musickit/UnitGenerator.h>

static MKMasterUGStruct _masterUGStruct = {
   9 /* nArgs */,
   {0,4,0,0,5,0,0,0,0,0,0,0,0} /* globalSymCount */,
   {1,0,0} /* fixupCount */
};

+(MKMasterUGStruct *)masterUGPtr { return &_masterUGStruct; }

+ (void)initialize  /* Sent once on class start-up. */
{
#  define OFFSET(_x) _x.value.i
   static DSPSymbol _argSymbols[9];
   static DSPSymbol _symbolsX[] = {
      {DSP_LC_X,"orch_biquad_1_ainp","GRI"},
      {DSP_LC_X,"orch_biquad_1_aout","GRI"},
      {DSP_LC_X,"orch_biquad_1_s1","GRI"},
      {DSP_LC_X,"orch_biquad_1_s2","GRI"}
   };
   static DSPSymbol _symbolsY[] = {
      {DSP_LC_Y,"orch_biquad_1_bqa1","GRI"},
      {DSP_LC_Y,"orch_biquad_1_bqa2","GRI"},
      {DSP_LC_Y,"orch_biquad_1_bqb1","GRI"},
      {DSP_LC_Y,"orch_biquad_1_bqb2","GRI"},
      {DSP_LC_Y,"orch_biquad_1_go2","GRI"}
   };
   _masterUGStruct.symbols[(int)DSP_LC_X] = _symbolsX;
   _masterUGStruct.symbols[(int)DSP_LC_Y] = _symbolsY;
   OFFSET(_symbolsX[0]) = 1;
   OFFSET(_symbolsX[1]) = 0;
   OFFSET(_symbolsX[2]) = 3;
   OFFSET(_symbolsX[3]) = 2;
   OFFSET(_symbolsY[0]) = 2;
   OFFSET(_symbolsY[1]) = 1;
   OFFSET(_symbolsY[2]) = 4;
   OFFSET(_symbolsY[3]) = 3;
   OFFSET(_symbolsY[4]) = 0;
   _argSymbols[(int)ainp] = _symbolsX[0];
   _argSymbols[(int)aout] = _symbolsX[1];
   _argSymbols[(int)s1] = _symbolsX[2];
   _argSymbols[(int)s2] = _symbolsX[3];
   _argSymbols[(int)bqa1] = _symbolsY[0];
   _argSymbols[(int)bqa2] = _symbolsY[1];
   _argSymbols[(int)bqb1] = _symbolsY[2];
   _argSymbols[(int)bqb2] = _symbolsY[3];
   _argSymbols[(int)go2] = _symbolsY[4];
   _masterUGStruct.argSymbols = _argSymbols;
   return;
}
