
/* Generated by Interface Builder */

#import <AppKit/AppKit.h>

@interface Controller: NSObject
{
    id ampPots;
    id ampFields;
    id myMidiHandler;
    id slide;
    id regHole;
    id regMode;
}

- play:sender;
- changeVelocity: (double) velocity;
- changeAmps:sender;
- changeAmpsQuick: (double) inValue : (double) outValue;
- changeSlide:sender;
- changeSlideQuick: (double) value registerMode: (int) mode registerHole: (double) regValue;
- changeEmbouchure:sender;
- changeEmbouchureQuick:(double) value;
- changeNoiseVolume:sender;
- changeNoiseVolumeQuick:(double) value;

@end
