
/* Generated by Interface Builder */

#import <objc/Object.h>
#import "ResoController.h"

@interface Xforms:Object
{
}

- freqRespData: (P_ZRec *) data Array: (float *) f Size: (int) size;
- zeroPad: (float *) f  From: (int) size1 To: (int) size2;
- logMag: (int) size array: (float *) f floor: (float) fl norm: (float) nrm;

@end
