
/* Generated by Interface Builder */

/* Skeleton transfrom Object: Currently, the only method in this object used is the logMag object
(derived from one of Perry R. Cook's methods) which does an in place log mag on
the sent data. The data is normalized */

#import "Xforms.h"
#import <math.h>

@implementation Xforms

- freqRespData: (P_ZRec *) data Array: (float *) f Size: (int) size
{
	register int i;
	register float b1,b2;
	
	for(i = 0; i < size; i++) {
	
	}
	
	return self;
}

- zeroPad: (float *) f  From: (int) size1 To: (int) size2;
{
	register int i;
	
	for(i = size1; i < size2; i++) f[i] = 1;
	return self;
}

- logMag: (int) size array: (float *) f floor: (float) fl norm: (float) nrm

/* calculates the log magnitude of the data, normalized to range of one */

{
    int i;
    float t1=0.0,t=0.0,t2=-12;
    t2 = fl / 5.0;
    f[0] *= 2*f[0];
    if (f[0] > t1)
        t1 = f[0];
    for (i=1;i<size;i++)	{
    	t = f[i]*f[i];
	f[i] = t;
	if (t>t1)
	   t1 = t;
    }
    for (i=0;i<size;i++)	{
    	if (nrm > 0) t = log((double) f[i]/(nrm * nrm));
	else t = log(f[i]/t1);
	if (t<t2)
	   t = t2;
	f[i] = 1 - t/t2;
    }
    return self;
}

@end
