
/* Generated by Interface Builder */

#import <appkit/View.h>
#import "ResoController.h"

@interface Z3DPlaneView:View
{
	P_ZRec data3D;
	float yRad;
	float gain;
	id gainField, gainSlid;
}

+ newFrame:(NXRect*)frameRect;

- setPoles: (P_ZRec *) thePandZ;
- drawSelf: (NXRect *) rects : (int) rectCount;
- updateGain: sender;
- setGainField: anObject;
- setGainSlid: anObject;
/* private */

@end
