
/* Generated by Interface Builder */

#import <appkit/View.h>
#import "ResoController.h"

/*   ZPlaneView is a class I made which draws poles and zeroes from radii and angles*/

@interface ZPlaneView:View
{
	int circle_gState;
	id drag_cache;
	P_ZRec *P_Zdata;
	int weBeCaching;
	float yRad;
}


+ newFrame: (NXRect *) frameRect;
- drawSelf: (NXRect *) rects : (int) rectCount;
- drawZeroAt: (float) x : (float) y;
- drawPoleAt: (float) x : (float) y;
- drawPoles: (int) pz_num;
- (BOOL) dragP_Z: (int) pz_num;
- mouseDown: (NXEvent *) theEvent;

@end
