
/* Generated by Interface Builder */

#include <libc.h>
#include <strings.h>

extern int Pid;

#import "Stopit.h"

@implementation Stopit

- terminate:sender
{
	if (Pid > 0) {
		char s[10] = "kill ";
		char num[10];

		sprintf(num,"%d",Pid);
		strcat(s,num);
		system(s);
		}

	[super terminate:self];
}


@end
