#ifndef __MK_MyApp_H___
#define __MK_MyApp_H___

/* Generated by Interface Builder */

#import <AppKit/AppKit.h>
#define TEXT 0

@interface ScorePlayerController: NSObject
{
	id button;
	id tempoSlider;
	id tempoTitle;
	id tempoTextField;
	id theMainWindow;
	id tooFastErrorMsg;
	id editFileItem;
	id saveAsFileItem;
	id soundSavePanel;
	id dspCommandsSavePanel;
	id NeXTDacMuteSwitch;
	id NeXTDacVolumeSlider;
 	id timeCodeButton;
 	id timeCodePortMatrix;
 	id timeCodeTextField;
	id serialPortDeviceNameField;
	id serialPortDeviceMatrix;
}


-help:sender;
-openEditFile:sender;
- deviceSpecificSettings:sender;
- setSoundOutFrom:sender;
- saveAsDefaultDevice:sender;
- appWillInit:sender;
- setTempoFrom:sender;
- playStop:sender;
- selectFile:sender;
- showErrorLog:sender;
- saveScoreAs:sender;
- setAD64xConsumer:sender;
- setAD64xProfessional:sender;
- setTimeCodeSynch:sender;
- setTimeCodeSerialPort:sender;
@end

#endif
