/* Generated by the NeXT Interface Builder */

#import <AppKit/AppKit.h>
#import <MusicKit/MusicKit.h>

@interface MidiEcho : NSObject
{
    id myFilter;
    MKMidi *midi;
    id infoPanel;
    id stringTable;
}
- (void)setMidiDev:sender;
- (void)go:sender;
- (void)setDelayFrom:sender;
- (void)showInfoPanel:sender;

@end
