/* Generated by Interface Builder */

#import <objc/Object.h>

@interface Looching:Object
{
    id	inVibRate;
    id	inVibWidth;
    id	outVibRate;
    id	outVibWidth;
    id	inSpread;
    id	outSpread;
}

- setInVibRate:anObject;
- setInVibWidth:anObject;
- setOutVibRate:anObject;
- setOutVibWidth:anObject;
- setInSpread:anObject;
- setOutSpread:anObject;
- displaySpread:sender;
- setParams:sender;
- StartAndStop:sender;
- trArnie:sender;
- trBach:sender;
- displayVibWidth:sender;
- displayVibRate:sender;
- trDrone:sender;
- trMorning:sender;
- trOriginal:sender;

@end
