
/* Generated by Interface Builder */

#import <AppKit/AppKit.h>

@interface Controller: NSObject
{
    id ampPots;
    id ampFields;
    id myMidiHandler;
}

- play:sender;
- changeVelocity: (double) velocity;
- changeAmps:sender;
- changeAmpsQuick: (double) inValue : (double) outValue;
- changeSlide:sender;
- changeSlideQuick:(double) value;
- changeEmbouchure:sender;
- changeEmbouchureQuick:(double) value;
- changeNoiseVolume:sender;
- changeNoiseVolumeQuick:(double) value;

@end
