#
# $Id$
#
# Build script for the MusicKit Examples on GNUstep systems.
# See Makefile.in for the build process on MacOS X systems.
#
# Leigh Smith <leigh@leighsmith.com>
#
# Copyright (c) 2005, The MusicKit Project.  All rights reserved.
#
# Permission is granted to use and modify this code for commercial and 
# non-commercial purposes so long as the author attribution and copyright 
# messages remain intact and accompany all relevant code.
#

SUBPROJECTS = \
	MultipleSoundPlayer \
	MidiEcho \
	MidiLoop \
	MidiPlay \
	MidiRecord \
#	PerformerExample \
#	PlayNote \
#	playpart \
#	playscorefile \
#	playscorefile2 \
#	playscorefilemidi \
#	SineGen \
#	exampsynthpatch \
#	exampunitgenerator \
	mixscorefiles \
	mixsounds \
#	process_soundfiles_dsp \
#	ResonSound \
#	QP

include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/aggregate.make
