#ifndef __MK_MyApp_H___
#define __MK_MyApp_H___

/* Generated by the NeXT Interface Builder */

#import <AppKit/AppKit.h>
#import <MusicKit/MusicKit.h>

@interface MidiPlayController : NSObject
{
    MKMidi *midiIn;
    id infoPanel;
    id stringTable;
}

- (void) applicationWillTerminate: (NSNotification *) aNotification;
- (IBAction) go:sender;

@end

#endif
