#ifndef __MK_MyApp_H___
#define __MK_MyApp_H___

/* Generated by the NeXT Interface Builder */

#import <appkit/appkit.h>
#import <appkit/Application.h>

@interface MyApp : Application
{
    id midiIn;
    id infoPanel;
    id stringTable;
}

- terminate:sender;
- go:sender;
- showInfoPanel:sender;

@end

#endif
