
/* Generated by Interface Builder */

#import <AppKit/AppKit.h>
#import "ResoController.h"

@interface Z3DPlaneView: NSView
{
	P_ZRec data3D;
	float yRad;
	float gain;
	id gainField, gainSlid;
}

+ newFrame:(NSRect*)frameRect;

- setPoles: (P_ZRec *) thePandZ;
- drawSelf: (NSRect *) rects : (int) rectCount;
- updateGain: sender;
- setGainField: anObject;
- setGainSlid: anObject;
/* private */

@end
